# Q1) Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
x = np.zeros(10)
print(x)
print("fifth value is 1")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
fifth value is 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


# Q2) Create a vector with values ranging from 10 to 49.

In [4]:
import numpy as np
v = np.arange(10,49)
print("Given vector:")
print(v)
print("Resultant vector")
v[1:-1]
print(v)

Given vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
Resultant vector
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Q3) Create a 3x3 matrix with values ranging from 0 to 8

In [1]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Q4) Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
import numpy as np
a = np.array([1,2,0,0,4,0])
print("Given array:")
print(a)
print("Indices of non-zero elements:")
result = np.where(a != 0)[0]
print(result)

Given array:
[1 2 0 0 4 0]
Indices of non-zero elements:
[0 1 4]


# Q5) Create a 10x10 array with random values and find the minimum and maximum values.

In [15]:
import numpy as np
x = np.random.random((10,10))
print("Given array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Given array:
[[0.96348788 0.0258114  0.77590942 0.25885277 0.63481599 0.75787141
  0.7490715  0.5060657  0.31304968 0.08066708]
 [0.0187152  0.98677767 0.86878011 0.16880229 0.25597664 0.90275879
  0.0949518  0.19819426 0.04398098 0.1496977 ]
 [0.2235951  0.91647762 0.07360172 0.591975   0.79787354 0.84009448
  0.58810529 0.79823422 0.91405583 0.51876337]
 [0.69024202 0.6889434  0.36451734 0.47552272 0.25084574 0.37710329
  0.8543638  0.46214315 0.21769597 0.3992494 ]
 [0.76876614 0.08812213 0.75525731 0.94904598 0.036385   0.3055697
  0.31669658 0.79180104 0.52047121 0.769913  ]
 [0.96358166 0.83644618 0.89491332 0.26601819 0.5869458  0.79146178
  0.97118432 0.14481677 0.30167992 0.41210659]
 [0.63473506 0.36138601 0.94795136 0.93740226 0.11231216 0.12775991
  0.73166266 0.17217331 0.53615292 0.83005987]
 [0.47604513 0.64268792 0.29738392 0.56921071 0.96148073 0.34541532
  0.858539   0.05418847 0.54591837 0.79750045]
 [0.92508915 0.84021546 0.5098278  0.10044813 0.56985376 0.81561949


# Q6) Create a random vector of size 30 and find the mean value.

In [1]:
import numpy as np
x = np.random.random(30)
print("Given array:")
print(x)
a = x.mean()
print("Mean value:")
print(a)

Given array:
[0.21900242 0.58390881 0.827105   0.89028086 0.98945362 0.78607322
 0.4817476  0.89239449 0.62652548 0.69056253 0.79788793 0.78176405
 0.60707942 0.20823198 0.82444154 0.71630361 0.84594832 0.17269889
 0.96184962 0.07758369 0.5420228  0.41412232 0.57186319 0.3763768
 0.39994392 0.20630531 0.04858414 0.68411894 0.42843999 0.04775547]
Mean value:
0.5566791985640533
